apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sonar-deployment
  #namespace: sonar
  labels:
    app: postgres-sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sonar
  template:
    metadata:
      labels:
        app: postgres-sonar
    spec:
      securityContext:
        fsGroup: 2000 
      containers:
      - name: postgres-sonar
        image: bitnami/postgresql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        envFrom:
        - configMapRef:
            name: postgres-sonar-cm
        volumeMounts:
        - name: postgres-sonar
          mountPath: /bitnami/postgresql
        resources:
          requests:
            cpu: 500m
            memory: "1024Mi"
          limits:
            cpu: 1000m
            memory: "2048Mi"
      volumes:
      - name: postgres-sonar
        persistentVolumeClaim:
          claimName: postgres-sonar-pvc